This is makeindex, version 2.15 [TeX Live 2014] (kpathsea + Thai support).
Scanning style file ./PHDbase.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file PHDbase.acn....done (38 entries accepted, 0 rejected).
Sorting entries....done (211 comparisons).
Generating output file PHDbase.acr....done (88 lines written, 0 warnings).
Output written in PHDbase.acr.
Transcript written in PHDbase.alg.
